/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Movie = IDL.Record({
  'title' : IDL.Text,
  'cast' : IDL.Vec(IDL.Text),
  'synopsis' : IDL.Text,
  'phase' : IDL.Nat,
  'releaseYear' : IDL.Nat,
  'officialMarvelLink' : IDL.Text,
});
export const Feedback = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'addMovie' : IDL.Func([IDL.Text, Movie], [], []),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
  'getMovie' : IDL.Func([IDL.Text], [Movie], ['query']),
  'submitFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Movie = IDL.Record({
    'title' : IDL.Text,
    'cast' : IDL.Vec(IDL.Text),
    'synopsis' : IDL.Text,
    'phase' : IDL.Nat,
    'releaseYear' : IDL.Nat,
    'officialMarvelLink' : IDL.Text,
  });
  const Feedback = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'addMovie' : IDL.Func([IDL.Text, Movie], [], []),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
    'getMovie' : IDL.Func([IDL.Text], [Movie], ['query']),
    'submitFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };